# This file was generated by GoReleaser. DO NOT EDIT.
cask "plicense" do
  name "plicense"
  desc "A license management CLI written in Go"
  homepage "https://github.com/dd3vahmad/plicense"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plicense"

  on_macos do
    on_intel do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_darwin_x86_64.tar.gz"
      sha256 "fcb85f915f2efc1ec00106a268ff155d0abd63bf87fe017367140768ce90bdf8"
    end
    on_arm do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_darwin_arm64.tar.gz"
      sha256 "2683557beb899edd88c81aa0503eaa5a9bf01e916db87a7b96c971c299e9842b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_linux_x86_64.tar.gz"
      sha256 "8316c939f011677db4aec3bfdb7ca818caaac4cab24c52c6777c9d7948aecfa5"
    end
    on_arm do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_linux_arm64.tar.gz"
      sha256 "61592a0f1ea8d38f5cf404e52c3a19b29f7a852d31e56bb07afd7a4e30b77a35"
    end
  end

  # No zap stanza required
end
