# This file was generated by GoReleaser. DO NOT EDIT.
cask "plicense" do
  name "plicense"
  desc "A license management CLI written in Go"
  homepage "https://github.com/dd3vahmad/plicense"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plicense"

  on_macos do
    on_intel do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_darwin_x86_64.tar.gz"
      sha256 "e010d147a98e89671e1df062427bce75516d83d839cad91f1045a47dcd0c7188"
    end
    on_arm do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_darwin_arm64.tar.gz"
      sha256 "2f5f4daf5b48fd99ca0b20b75a46d6f22d155699f2bcc3f93a984fd432aa3e91"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_linux_x86_64.tar.gz"
      sha256 "b4f4bf3ee48e63ce742114d949c14d08006e031783309e200c0896b55ab147ae"
    end
    on_arm do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_linux_arm64.tar.gz"
      sha256 "30196aa78fe112bd14a7936f957328dc5d1a4201b8f6f233183953ea223d180d"
    end
  end

  # No zap stanza required
end
