# This file was generated by GoReleaser. DO NOT EDIT.
cask "plicense" do
  name "plicense"
  desc "A license management CLI written in Go"
  homepage "https://github.com/dd3vahmad/plicense"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plicense"

  on_macos do
    on_intel do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_darwin_x86_64.tar.gz"
      sha256 "b845fea02d067839724b30134c280a8f1ccc75cf71f5031980cce5556e165596"
    end
    on_arm do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_darwin_arm64.tar.gz"
      sha256 "e8e0a1f211fade152750dc45294f7a0e48f203dd12ea56eee1895c1a31f9eda9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_linux_x86_64.tar.gz"
      sha256 "27e30cbd0b29d7ea94f67d1aab03050a53d3523972e9211bc1031243439b8f88"
    end
    on_arm do
      url "https://github.com/dd3vahmad/plicense/releases/download/v#{version}/plicense_linux_arm64.tar.gz"
      sha256 "456c8eb5ac3eb609e505edf0903bcfc2bdf982f18b06ce18a59fabc2e1bdb1ec"
    end
  end

  # No zap stanza required
end
